Repository dnsimple/dnsimple-developer, pull requests merged in 2018-10, with the labels that each got.

#168 Document checkZoneRecordDistribution
  content/v2/zones/records.markdown
  fixtures/v2/checkZoneRecordDistribution/error.http
  fixtures/v2/checkZoneRecordDistribution/failure.http
  fixtures/v2/checkZoneRecordDistribution/success.http
Labels: enhancement, ready-for-review

#166 OpenAPI: zone distribution
  content/v2/openapi.yml
Labels: ready-for-review

#176 Update information about test credit cards numbers
  content/sandbox.markdown
Labels: enhancement
