Repository dnsimple/dnsimple-developer, pull requests merged in 2021-01, with the labels that each got.

#285 Add the first use-case tutorial on how to register a domain
  content/use-cases.markdown
  content/use-cases/domain-registration.markdown
  layouts/sidebar.html
  layouts/v2-sidebar.html
Labels: enhancement

#307 Syncs marker CSS with the support site
  content/assets/css/_application.scss
Labels: task

#308 Update the domain registration tutorial copy
  content/use-cases.markdown
  content/use-cases/domain-registration.markdown
Labels: enhancement

#309 Update and cleanup styles
  content/assets/bootstrap/config.json
  content/assets/bootstrap/css/bootstrap.css
  content/assets/bootstrap/js/bootstrap.js
  content/assets/css/_application.scss
  content/assets/css/_mixins.scss
  content/assets/css/_template.scss
  content/assets/css/_typography.scss
  content/assets/css/style.scss
  content/assets/images/border.jpg
  content/assets/images/dnsimple-footer.svg
  layouts/default.html
  layouts/footer.html
  layouts/header.html
  layouts/sidebar.html
  layouts/v2-sidebar.html
  layouts/v2.html
  package.json
  webpack.config.js
  yarn.lock
Labels: task

#314 Mark Email from/to as deprecated
  content/v2/domains/email-forwards.markdown
  content/v2/openapi.yml
  fixtures/v2/api/createEmailForward/created.http
  fixtures/v2/api/deleteEmailForward/success.http
  fixtures/v2/api/getEmailForward/success.http
Labels: change-api, task
