Repository dnsimple/dnsimple-developer, pull requests merged in 2021-04, with the labels that each got.

#331 Tabs component
  Rakefile
  content/assets/css/_tabs.scss
  content/assets/css/style.scss
  package.json
  src/components/tabs.vue
  src/index.js
  webpack.config.js
  yarn.lock
Labels: enhancement, ready-for-review

#338 Mark getDomainPrices as Public preview
  content/v2/openapi.yml
  content/v2/registrar.markdown
Labels: change-api, ready-for-review

#332 Issue certificates use-case
  content/use-cases.markdown
  content/use-cases/issue-certificates.markdown
Labels: enhancement
