Repository dnsimple/dnsimple-developer, pull requests merged in 2021-03, with the labels that each got.

#323 Remove the required flag for Template's description
  content/v2/openapi.yml
  content/v2/templates.markdown
Labels: bug, ready-for-review

#324 Expand documentation about this repo
  CONTRIBUTING.md
  README.md
Labels: enhancement

#325 Documents getDomanPrices endpoint
  content/v2/openapi.yml
  content/v2/registrar.markdown
  fixtures/v2/api/getDomainPrices/failure.http
  fixtures/v2/api/getDomainPrices/success.http
Labels: enhancement

#328 Add documentation for Secondary DNS API
  content/v2/openapi.yml
  content/v2/secondary-dns.markdown
  fixtures/v2/api/createPrimaryServer/created.http
  fixtures/v2/api/createSecondaryZone/created.http
  fixtures/v2/api/getPrimaryServer/success.http
  fixtures/v2/api/linkPrimaryServer/success.http
  fixtures/v2/api/listPrimaryServers/success.http
  fixtures/v2/api/unlinkPrimaryServer/success.http
Labels: change-api, enhancement
