Repository dnsimple/dnsimple-developer, pull requests merged in 2022-04, with the labels that each got.

#391 Document the webhook delivery and retry logic
  Rakefile
  _redirects
  content/v2/webhooks/events.markdown
  content/v2/webhooks/webhooks.markdown
  layouts/sidebar.html
Labels: enhancement

#394 Fixes broken webhooks/events link
  content/v2/webhooks/webhooks.markdown
Labels: bug, ready-for-review

#395 Bumps ruby to 3.0.4
  .tool-versions
  .travis.yml
  Gemfile
  Gemfile.lock
Labels: dependencies, task
