Repository dnsimple/dnsimple-developer, pull requests merged in 2022-09, with the labels that each got.

#426 Add OpenAPI response schema for 400 status code responses
  content/v2/openapi.yml
Labels: enhancement, change-api

#425 Improve documentation about error responses
  content/v2.markdown
  content/v2/accounts.markdown
  content/v2/certificates.markdown
  content/v2/contacts.markdown
  content/v2/domains.markdown
  content/v2/domains/collaborators.markdown
  content/v2/domains/dnssec.markdown
  content/v2/domains/email-forwards.markdown
  content/v2/domains/pushes.markdown
  content/v2/identity.markdown
  content/v2/registrar.markdown
  content/v2/registrar/auto-renewal.markdown
  content/v2/registrar/delegation.markdown
  content/v2/registrar/whois-privacy.markdown
  content/v2/secondary-dns.markdown
  content/v2/services.markdown
  content/v2/services/domains.markdown
  content/v2/templates.markdown
  content/v2/templates/domains.markdown
  content/v2/templates/records.markdown
  content/v2/tlds.markdown
  content/v2/vanity.markdown
  content/v2/webhooks/webhooks.markdown
  content/v2/zones.markdown
  content/v2/zones/records.markdown
Labels: enhancement

#427 Bumps node version
  .tool-versions
Labels: dependencies
