Repository dnsimple/dnsimple-developer, pull requests merged in 2023-11, with the labels that each got.

#540 Cleanup unused logos
  dotnet.svg
  elixir.svg
  go.svg
  java.svg
  node.svg
  php.svg
  python.svg
  ruby.svg
  rust.svg
Labels: task

#541 Fix webapp configuration
  Gemfile
  Gemfile.lock
Labels: dependencies

#542 Update Zone model in the OpenAPI definition
  content/v2/openapi.yml
  content/v2/zones.markdown
  fixtures/v2/api/activateZoneService/success.http
  fixtures/v2/api/deactivateZoneService/success.http
  fixtures/v2/api/getZone/success.http
  fixtures/v2/api/listZones/success.http
Labels: documentation

#544 Add warnings about special quota limitation scenarios
  content/v2.markdown
  content/v2/registrar.markdown
Labels: documentation
