Repository dnsimple/dnsimple-developer, pull requests merged in 2023-07, with the labels that each got.

#496 Add OpenAPI entries for the new entrypoint to toggle DNS resolution on a zone
  content/v2/openapi.yml
Labels: enhancement

#499 Add developer entries for the new entrypoint to toggle DNS resolution on a zone
  content/v2/domains.markdown
  content/v2/registrar.markdown
  content/v2/secondary-dns.markdown
  content/v2/zones.markdown
Labels: enhancement

#503 Zone activation and deactivation endpoints are in preview
  content/v2/zones.markdown
Labels: enhancement

#501 Add RegistrantChange specification to OpenAPI definition
  .redocly.lint-ignore.yaml
  content/v2/openapi.yml
Labels: enhancement

#505 Document stateful trade webhooks
  content/v2/openapi.yml
  content/v2/webhooks/events.markdown
  fixtures/v2/webhooks/domain.registrant_change/status-cancelled.http
  fixtures/v2/webhooks/domain.registrant_change/status-started.http
Labels: enhancement

#506 Refresh feature announcements
  content/assets/images/features/whats-new-april-2023.png
  content/assets/images/features/whats-new-summer-2023.png
  content/index.html
Labels: task

#509 Scope registrant changes under registrar
  content/v2/openapi.yml
Labels: bug

#510 Improve registrant change documentation
  content/v2/openapi.yml
Labels: enhancement
