Repository dnsimple/dnsimple-developer, pull requests merged in 2023-08, with the labels that each got.

#515 Update registrant change field
  content/v2/openapi.yml
Labels: enhancement

#517 Document optional "integrated_zones" parameter and behavior in Zone Records API
  content/v2/openapi.yml
  content/v2/zones/records.markdown
Labels: enhancement

#523 Remove redundant tags in OpenAPI spec
  content/v2/openapi.yml
Labels: bug

#521 Fixtures for contact management API
  fixtures/v2/api/checkRegistrantChange/error-contactnotfound.http
  fixtures/v2/api/checkRegistrantChange/error-domainnotfound.http
  fixtures/v2/api/checkRegistrantChange/success.http
  fixtures/v2/api/createRegistrantChange/success.http
  fixtures/v2/api/deleteRegistrantChange/success.http
  fixtures/v2/api/getRegistrantChange/success.http
  fixtures/v2/api/listRegistrantChanges/success.http
  fixtures/v2/webhooks/domain.registrant_change_started/example.http
Labels: task

#524 Update deleteRegistrantChange responses and fixtures
  content/v2/openapi.yml
  fixtures/v2/api/deleteRegistrantChange/success.http
  fixtures/v2/api/deleteRegistrantChange/success_async.http
Labels: enhancement, change-api
