Repository dnsimple/dnsimple-developer, pull requests merged in 2024-02, with the labels that each got.

#557 Add new docs section for DNS Analytics
  content/v2.markdown
  content/v2/dns-analytics.markdown
  fixtures/v2/api/dnsAnalytics/success.http
  layouts/sidebar.html
Labels: task

#558 Add new DNS analytics endpoint to OpenAPI spec
  content/v2/openapi.yml
Labels: documentation

#565 Document Domain Restore API
  content/v2/registrar.markdown
  fixtures/v2/api/getDomainRestore/success.http
  fixtures/v2/api/restoreDomain/success.http
Labels: documentation

#564 Domain Restore OpenAPI spec
  content/v2/openapi.yml
Labels: documentation

#553 Dynamically loading the "whats new"
  content/index.html.erb
  lib/default.rb
Labels: site-generator, task

#566 Add dependabot instructions to update JS files
  .github/dependabot.yml
Labels: site-generator
