Repository dnsimple/dnsimple-developer, pull requests merged in 2025-02, with the labels that each got.

#760 Expand `search.json` to include more searchable fields
  lib/search.rb
  netlify.toml
  src/index.js
Labels: javascript

#762 Improving Search Experience: Use the search widget
  layouts/default.html
  layouts/header.html
  src/index.js
  src/search.js
Labels: javascript

#764 Search: Remove 404 from search results
  lib/search.rb
Labels: documentation

#767 Search: Refine the button
  content/assets/css/_template.scss
  layouts/header.html
Labels: javascript

#766 Adding marketing banner to top of developer site
  banners.yml
  content/assets/css/_template.scss
  layouts/banner.html
  layouts/header.html
  lib/default.rb
Labels: site-generator
